# Generated by Django 5.1 on 2025-01-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('ordering_persons', models.ManyToManyField(blank=True, related_name='building_sites', to=settings.AUTH_USER_MODEL)),
                ('office_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='building_site.siteofficeaddress')),
            ],
        ),
    ]
