# Generated by Django 5.1 on 2025-01-11 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_site', '0001_initial'),
        ('home', '0001_initial'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingsite',
            name='laboratories',
            field=models.ManyToManyField(blank=True, related_name='building_sites', to='laboratory.laboratory'),
        ),
        migrations.AddField(
            model_name='buildingsite',
            name='ordering_persons',
            field=models.ManyToManyField(blank=True, related_name='building_sites', to='home.client'),
        ),
        migrations.AddField(
            model_name='buildingsite',
            name='office_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='building_site.siteofficeaddress'),
        ),
    ]
